stages:
  - clone
  - build
  - tests
  - deploy

.default:
  only:
    - push
  when: on_success

clone:
  stage: clone
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tvquangcs/xxx.git

build:
  when: always
  stage: build
  script:
    - npm ci
  artifacts:
    when: always
    paths:
      - node_modules
    expire_in: 5 days

test-api:
  when: on_success
  stage: tests
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  script:
    - npx playwright test
  allow_failure: true
  artifacts:
    when: always
    paths:
      - ./playwright-report
    expire_in: 6 days

pre_deploy:
  stage: deploy
  dependencies:
    - test-api
  script:
    - echo pre deploy

auto_deploy:
  stage: deploy
  dependencies:
    - pre_deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: on_success
  script:
    - echo deploy to other env
