import { z } from 'zod';
import { test, expect } from '@playwright/test';
import { generateMock } from '@anatine/zod-mock';
import { paths, components } from '@api/types/pet-type';
import { schemas as autoGeneratedZodSchema } from '@api/zod-schemas/zodSchema';

const baseUrl = 'https://petstore3.swagger.io/api/v3';
type PetRequest = components['schemas']['Pet'];
type PetResponse = paths['/pet']['post']['responses']['200']['content']['application/json'];

test('validate with zod schema @api', async ({ request }) => {
  // manual create schema with zod
  const PetSchema = z.object({
    id: z.number(),
    name: z.string(),
    category: z.object({
      id: z.number(),
      name: z.string()
    }),
    photoUrls: z.array(z.string())
  });

  const petRequestPayload: PetRequest = {
    id: 123,
    name: 'Dog',
    category: { id: 1, name: 'Luna' },
    photoUrls: ['https://example.com/dog.jpg'],
    tags: [{ id: 1, name: 'friendly' }],
    status: 'available'
  };
  const res = await request.post(`${baseUrl}/pet`, {
    data: petRequestPayload
  });
  const resBody = await res.json();
  const responseData: PetResponse = resBody;
  expect(res.status()).toBe(200);
  expect(responseData.id).toBe(petRequestPayload.id);
  // validate response
  PetSchema.parse(resBody);
});

test('validate with Auto Generated zod schema @api', async ({ request }) => {
  // define generated zod schema
  const PetSchema = autoGeneratedZodSchema.Pet;
  // create request data following schema type
  const petData: PetRequest = {
    id: 123,
    name: 'Dog',
    category: { id: 1, name: 'Luna' },
    photoUrls: ['https://example.com/dog.jpg'],
    tags: [{ id: 1, name: 'friendly' }],
    status: 'available'
  };
  const res = await request.post(`${baseUrl}/pet`, {
    data: petData
  });
  const resBody = await res.json();
  // validate response schema
  const responseData: PetResponse = resBody;
  expect(res.status()).toBe(200);
  expect(responseData.id).toBe(petData.id);
  // validate response
  PetSchema.parse(resBody);
});

test('validate with auto generated zod schema and mock data @api', async ({ request }) => {
  const PetSchema = autoGeneratedZodSchema.Pet;
  // create pet with mock schema data
  const petMockData: PetRequest = generateMock(PetSchema);
  const res = await request.post(`${baseUrl}/pet`, {
    data: petMockData
  });
  const resBody = await res.json();
  const responseData: PetResponse = resBody;
  expect(res.status()).toBe(200);
  expect(responseData.id).toBe(petMockData.id);
  PetSchema.parse(resBody);
});
