#!/bin/sh

echo "🧑‍💻 Running lint-staged..."
npx lint-staged

STATUS=$?
if [ "$STATUS" -eq 1 ]; then
  echo "👮‍♂️ Commit blocked: Lint errors found in staged files 🚨"
  echo "🛠️ Fix them before committing 🤖"
  exit 1
elif [ "$STATUS" -ne 0 ]; then
  echo "💥 Unexpected error from lint-staged"
  exit $STATUS
fi

echo "🎉 No errors found. Let it go... 🚀"
exit 0
